---

- name: ensure powertop is installed
  dnf:
    name: powertop
    state: latest
  when: laptop_powersave_enable_powertop

- name: ensure powertop is enabled
  service:
    name: powertop
    enabled: yes
  when: laptop_powersave_enable_powertop

- name: ensure powertop is disabled
  service:
    name: powertop
    enabled: no
  when: not laptop_powersave_enable_powertop
