---

- name: ensure tuned is installed
  dnf:
    name: tuned
    state: latest
  when: laptop_powersave_enable_tuned
    

- name: Enable and start tuned.service
  service:
    name: tuned
    state: started
    enabled: yes
  when: laptop_powersave_enable_tuned

- name: Disable and stop tuned.service
  service:
    name: tuned
    state: stopped
    enabled: no
  when: not laptop_powersave_enable_tuned

- name: get active tuned profile
  shell: "tuned-adm active | grep 'Current active profile: {{ laptop_powersave_tuned_profile }}'"
  register: laptop_powersave_tuned_active_profile
  changed_when: False
  failed_when: laptop_powersave_tuned_active_profile.rc >= 2
  when: laptop_powersave_enable_tuned

- name: set tuned profile to {{ laptop_powersave_tuned_profile }}
  command: tuned-adm profile {{ laptop_powersave_tuned_profile }}
  when: (laptop_powersave_enable_tuned) and
        (laptop_powersave_tuned_active_profile.rc!=0)
